#!/usr/bin/env python3
"""Turn the checkboxes in ROADMAP.md into a progress report.

Reads every ``- [ ]`` / ``- [x]`` task in ROADMAP.md, groups them by the
``## Phase N` heading they sit under, and writes:

  * PROGRESS.md          — a full per-phase breakdown
  * README.md            — the summary table between the PROGRESS markers

The whole thing is idempotent: running it twice in a row produces no diff,
which is what lets the GitHub Action commit only when something really moved.

Usage
-----
    python scripts/build_progress.py             # rewrite both files
    python scripts/build_progress.py --check     # exit 1 if files are stale
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ROADMAP = REPO_ROOT / "ROADMAP.md"
PROGRESS = REPO_ROOT / "PROGRESS.md"
README = REPO_ROOT / "README.md"

START_MARKER = "<!-- PROGRESS:START -->"
END_MARKER = "<!-- PROGRESS:END -->"

PHASE_PAT = re.compile(r"^##\s+(Phase\s+\d+[^\n]*)$")
TASK_PAT = re.compile(r"^\s*[-*]\s+\[([ xX])\]\s+(.+?)\s*$")

BAR_WIDTH = 28


@dataclass
class Phase:
    name: str
    tasks: list[tuple[bool, str]] = field(default_factory=list)

    @property
    def done(self) -> int:
        return sum(1 for ok, _ in self.tasks if ok)

    @property
    def total(self) -> int:
        return len(self.tasks)

    @property
    def pct(self) -> float:
        return 100.0 * self.done / self.total if self.total else 0.0


def parse_roadmap(text: str) -> list[Phase]:
    phases: list[Phase] = []
    current: Phase | None = None
    for line in text.splitlines():
        heading = PHASE_PAT.match(line)
        if heading:
            current = Phase(name=heading.group(1).strip())
            phases.append(current)
            continue
        task = TASK_PAT.match(line)
        if task and current is not None:
            current.tasks.append((task.group(1).lower() == "x", task.group(2).strip()))
    return [p for p in phases if p.total]


def bar(pct: float, width: int = BAR_WIDTH) -> str:
    filled = round(width * pct / 100)
    return "█" * filled + "░" * (width - filled)


def status_word(pct: float) -> str:
    if pct >= 100:
        return "done"
    if pct > 0:
        return "in progress"
    return "not started"


def summary_table(phases: list[Phase]) -> str:
    done = sum(p.done for p in phases)
    total = sum(p.total for p in phases)
    pct = 100.0 * done / total if total else 0.0

    lines = [
        f"**Overall: {done} / {total} chapters ({pct:.0f}%)**",
        "",
        f"`{bar(pct)}` {pct:.0f}%",
        "",
        "| Phase | Progress | Done | Status |",
        "|---|---|---|---|",
    ]
    for p in phases:
        lines.append(
            f"| {p.name} | `{bar(p.pct, 16)}` | {p.done}/{p.total} | {status_word(p.pct)} |"
        )
    return "\n".join(lines)


def progress_page(phases: list[Phase]) -> str:
    # The header totals come from summary_table(); this function only adds the
    # per-phase breakdown beneath it.
    out = [
        "# Progress",
        "",
        "<!-- Generated by scripts/build_progress.py — do not edit by hand. -->",
        "<!-- Tick boxes in ROADMAP.md, then run `make progress`.          -->",
        "",
        f"_Last built: {date.today().isoformat()}_",
        "",
        summary_table(phases),
        "",
        "---",
        "",
    ]
    for p in phases:
        out += [f"## {p.name}", "", f"`{bar(p.pct)}` **{p.done}/{p.total}** ({p.pct:.0f}%)", ""]
        for ok, task in p.tasks:
            out.append(f"- [{'x' if ok else ' '}] {task}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def splice_readme(readme_text: str, block: str) -> str:
    if START_MARKER not in readme_text or END_MARKER not in readme_text:
        return readme_text
    head, rest = readme_text.split(START_MARKER, 1)
    _, tail = rest.split(END_MARKER, 1)
    return f"{head}{START_MARKER}\n{block}\n{END_MARKER}{tail}"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs are out of date")
    args = ap.parse_args(argv)

    if not ROADMAP.exists():
        print(f"ROADMAP.md not found at {ROADMAP}", file=sys.stderr)
        return 2

    phases = parse_roadmap(ROADMAP.read_text(encoding="utf-8"))
    if not phases:
        print("No '## Phase N' sections with checkboxes found in ROADMAP.md", file=sys.stderr)
        return 2

    new_progress = progress_page(phases)
    old_progress = PROGRESS.read_text(encoding="utf-8") if PROGRESS.exists() else ""

    new_readme = old_readme = ""
    if README.exists():
        old_readme = README.read_text(encoding="utf-8")
        new_readme = splice_readme(old_readme, summary_table(phases))

    # The build date changes daily; ignore it when deciding staleness.
    def strip_date(s: str) -> str:
        return re.sub(r"_Last built: \d{4}-\d{2}-\d{2}_", "", s)

    stale = strip_date(old_progress) != strip_date(new_progress) or old_readme != new_readme

    if args.check:
        if stale:
            print("PROGRESS.md / README.md are stale — run `make progress`.", file=sys.stderr)
            return 1
        print("Progress files are up to date.")
        return 0

    PROGRESS.write_text(new_progress, encoding="utf-8")
    if README.exists():
        README.write_text(new_readme, encoding="utf-8")

    done = sum(p.done for p in phases)
    total = sum(p.total for p in phases)
    print(
        f"Progress: {done}/{total} chapters across {len(phases)} phases -> PROGRESS.md, README.md"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
